---
title: "Assignments STT 3830 - Fall 2019"
author: "Alan T. Arnholt"
date: 'Last Updated on: `r format(Sys.time(), "%b %d, %Y at %X")`'
output: 
  bookdown::html_document2: 
    highlight: textmate
    theme: yeti
    css: "../css/style.css"
---

**Aug 19:**

* Go over syllabus.
* Become familiar with the Appstate [RStudio server](https://mathr.math.appstate.edu/). You will use your Appstate user name and password to log in to the server.  You must be registered in the class to access the server.
* Sign-up for free accounts on [GitHub](https://github.com).
* When you register for a free individual GitHub account, request a [student discount](https://education.github.com) to obtain a few private repositories as well as unlimited public repositories.  Please use something similar to **first_name_last_name** as your username when you register with GitHub.  For example, my username on GitHub is *alanarnholt*. If you have a popular name such as John Smith, you may need to provide some other distinquishing characteristic in your **username**.  
* Once you have a GitHub account, send an email to arnholtat@appstate.edu with a Subject line of **STT3830 - GitHub Username**, and tell me in the body of your email your first name, last name, and your GitHub username.

* Homework: 
    + Watch this [video (14 minutes)](https://www.youtube.com/watch?v=ZFaWxxzouCY&list=PLjTlxb-wKvXNSDfcKPFH2gzHGyjpeCZmJ&index=3) which provides some background on asking questions.  
    + Read this stackoverflow thread details how to create a [minimal R reproducible example](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example/5963610#5963610). 
    + Read [How To Ask Questions The Smart Way](http://www.catb.org/~esr/faqs/smart-questions.html) by Eric Raymond and Rick Moen and heed their advice.
    + Read [Getting used to R, RStudio, and R Markdown](https://ismayc.github.io/rbasics-book/)

**Aug 21:**

* In class lecture: Review of one and two sample inference, permutation tests, and bootstrap procedures --- take notes

* [Statistics Review](https://stat-ata-asu.github.io/STT3851ClassRepo/Rmarkdown/StatReview.html)
* Link to [Day One Activity and Code](https://stat-ata-asu.github.io/STT3851ClassRepo/Rmarkdown/DayOne.html)
    
    ```{block2, note-text, type='rmdnote'}
Most GitHub Classroom assignments due dates are 5 p.m. Friday.
```  

* Homework: Watch the following Videos:
    + [Phillip Guo's Unix-like command line tutorials (Four tutorials about 10 minutes each)](http://www.pgbovine.net/command-line-tutorial.htm)
    + [Phillip Guo's Basic Git and Github tutorials (Three tutorials about 10 minutes each)](http://www.pgbovine.net/git-tutorial.htm)
    + [Clone a GitHub Repo with RStudio (Video)](https://www.youtube.com/watch?v=YxZ8J2rqhEM) (5:05)

**Aug 23:**

* Before class watch the following Videos:
    + [Phillip Guo's Unix-like command line tutorials (Four tutorials about 10 minutes each)](http://www.pgbovine.net/command-line-tutorial.htm)
    + [Phillip Guo's Basic Git and Github tutorials (Three tutorials about 10 minutes each)](http://www.pgbovine.net/git-tutorial.htm)
    + [Clone a GitHub Repo with RStudio (Video)](https://www.youtube.com/watch?v=YxZ8J2rqhEM) (5:05)
* In class lecture: Review of one and two sample inference --- take notes
* [Statistics Review](https://stat-ata-asu.github.io/STT3851ClassRepo/Rmarkdown/StatReview.html)

* Homework:
    + Read Chapters 1-2 of [bookdown: Authoring Books and Technical Documents with R Markdown](https://bookdown.org/yihui/bookdown/)
    + Watch [Lab: Introduction to R](https://www.youtube.com/watch?v=jwBgGS_4RQA) (14:12)
    + Reproduce [Modified Introduction to R (Lab1)](https://stat-ata-asu.github.io/ISLR-CHAP2-LAB-SC/Lab1-Solution.html).  Accept assignment from GitHub Classroom. Due Aug 30 

**Aug 26:**

* Before class:
    + Read/review [Getting used to R, RStudio, and R Markdown](https://ismayc.github.io/rbasics-book/)
    + Read the [Git and GitHub](http://r-pkgs.had.co.nz/git.html) chapter from Hadley Wickham's book [R Packages](http://r-pkgs.had.co.nz/)
* Follow the directions from [Happy Git and GitHub for the useR](http://happygitwithr.com/) to [Introduce yourself to Git](http://happygitwithr.com/hello-git.html), [Connect to GitHub](http://happygitwithr.com/push-pull-github.html), and [Cache credentials for HTTPS](http://happygitwithr.com/credential-caching.html).
* Read/review Chapters 1-2 of [bookdown: Authoring Books and Technical Documents with R Markdown](https://bookdown.org/yihui/bookdown/)


**Aug 28:**

* In class lecture: Review of one and two sample inference, permutation tests, and bootstrap procedures --- take notes
* [Statistics Review](https://stat-ata-asu.github.io/STT3851ClassRepo/Rmarkdown/StatReview.html)
* Use an avatar or picture on your GitHub account



**Aug 30:**


* [Overplotting Examples and possible Solutions](https://stat-ata-asu.github.io/STT3851ClassRepo/Rmarkdown/HousingData.html)

* Due TODAY:
    + Reproduce [Modified Introduction to R (Lab1)](https://stat-ata-asu.github.io/ISLR-CHAP2-LAB-SC/Lab1-Solution.html).  Accept assignment from GitHub Classroom. Due Aug 30 
    
* Homework:  Complete [Data Camp Introduction to the Tidyverse](https://www.datacamp.com/courses/introduction-to-the-tidyverse) --- Due Sep 6


~~**Sep 2:**~~ **No Class - State Holiday**



**Sep 4:**

* Homework:  Complete [Data Camp Introduction to the Tidyverse](https://www.datacamp.com/courses/introduction-to-the-tidyverse) --- Due Sep 6


**Sep 6:**


* Due TODAY: [Data Camp Introduction to the Tidyverse](https://www.datacamp.com/courses/introduction-to-the-tidyverse) --- Due Sep 6


**Sep 9:**

* Homework:
    + [Data Camp Experimental Design in R](https://www.datacamp.com/courses/experimental-design-in-r) - Due Sep 13
    + Reproduce [Data Camp Experimental Design in R](https://www.datacamp.com/courses/experimental-design-in-r) - Accept assignment from GitHub Classroom - Due Sep 20


**Sep 11:**

* Go over [Chapter 2 Graphs](https://stat-ata-asu.github.io/STT3851ClassRepo/Rmarkdown/Chap2Slides.html)


**Sep 13:**

* Work Day
* Due TODAY: [Data Camp Experimental Design in R](https://www.datacamp.com/courses/experimental-design-in-r)  - Due Sep 13
* Reproduce [Data Camp Experimental Design in R](https://www.datacamp.com/courses/experimental-design-in-r)  - Accept assignment from GitHub Classroom - Due Sep 20

**Sep 16:**

* TBD


**Sep 18:**

* TBD


**Sep 20:**

* Due TODAY: Reproduce [Data Camp Experimental Design in R](https://www.datacamp.com/courses/experimental-design-in-r)  - Accept assignment from GitHub Classroom - Due Sep 20


**Sep 23:**

* Before class:
    + Read pages 59-82 of [ISLR](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf)
    + Watch [Simple Linear Regression and Confidence Intervals](https://www.youtube.com/watch?v=PsE9UqoWtS4) (13:01)
    + Watch [Hypothesis Testing ](https://www.youtube.com/watch?v=J6AdoiNUyWI) (8:24)
    + Watch [Multiple Linear Regression and Interpreting Regression Coefficients ](https://www.youtube.com/watch?v=1hbCJyM9ccs) (15:38)
* Discuss [Chapter 2 and 3 material](https://stat-ata-asu.github.io/STT3851ClassRepo/Rmarkdown/Chap2Slides.html)
* Homework: 
    +  Complete [Data Camp Correlation and Regression](https://www.datacamp.com/courses/correlation-and-regression) - Due Sep 27
    +  Reproduce [Data Camp Correlation and Regression (DataCamp1)](https://stat-ata-asu.github.io/CorrelationRegression/) - Accept assignment from GitHub Classroom - Due Oct 4


**Sep 25:**

* Discuss [Chapter 2 and 3 material](https://stat-ata-asu.github.io/STT3851ClassRepo/Rmarkdown/Chap2Slides.html)
* Homework: 
    +  Complete [Data Camp Correlation and Regression](https://www.datacamp.com/courses/correlation-and-regression) - Due Sep 27
    +  Reproduce [Data Camp Correlation and Regression (DataCamp1)](https://stat-ata-asu.github.io/CorrelationRegression/) - Accept assignment from GitHub Classroom - Due Oct 4


**Sep 27:**


* Discuss [Chapter 2 and 3 material](https://stat-ata-asu.github.io/STT3851ClassRepo/Rmarkdown/Chap2Slides.html)
* Homework: 
    +  Due TODAY: Complete [Data Camp Correlation and Regression](https://www.datacamp.com/courses/correlation-and-regression) - Due Sep 27
    +  Reproduce [Data Camp Correlation and Regression (DataCamp1)](https://stat-ata-asu.github.io/CorrelationRegression/) - Accept assignment from GitHub Classroom - Due Oct 4


**Sep 30:**

* Discuss [Chapter 2 and 3 material](https://stat-ata-asu.github.io/STT3851ClassRepo/Rmarkdown/Chap2Slides.html)
* Homework: Reproduce [Data Camp Correlation and Regression (DataCamp1)](https://stat-ata-asu.github.io/CorrelationRegression/) - Accept assignment from GitHub Classroom - Due Oct 4


**Oct 2:**

* Discuss [Chapter 2 and 3 material](https://stat-ata-asu.github.io/STT3851ClassRepo/Rmarkdown/Chap2Slides.html)
* Homework: Reproduce [Data Camp Correlation and Regression (DataCamp1)](https://stat-ata-asu.github.io/CorrelationRegression/) - Accept assignment from GitHub Classroom - Due Oct 4

**Oct 4:**

* Due TODAY: Reproduce [Data Camp Correlation and Regression (DataCamp1)](https://stat-ata-asu.github.io/CorrelationRegression/) - Accept assignment from GitHub Classroom - Due Oct 4

**Oct 7:**

* Before class:
    + Read pages 82-120 [ISLR](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf)
    + Watch [Model Selection and Qualitative Predictors](https://www.youtube.com/watch?v=3T6RXmIHbJ4) (14:51)
    
* Discuss [Chapter 2 and 3 material](https://stat-ata-asu.github.io/STT3851ClassRepo/Rmarkdown/Chap2Slides.html)

* Homework: 
    +  Reproduce [Lab: Linear Regression (Lab3)](https://stat-ata-asu.github.io/ISLR-CHAP3-LAB-SC/LabChap3-Solution.html) - Accept assignment from GitHub classroom - Due Oct 11
    +  [Data Camp Multiple and Logistic Regression](https://www.datacamp.com/courses/multiple-and-logistic-regression) - Due Oct 18
    +  Reproduce [Data Camp Multiple and Logistic Regression (DataCamp2)](https://stat-ata-asu.github.io/MultipleAndLogisticRegression/) - Accept assignment from GitHub Classroom - Due Oct 25


**Oct 9:**

* Before class:
    + Review pages 82-120 [ISLR](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf)
    + Watch [Interactions and Nonlinearity](https://www.youtube.com/watch?v=IFzVxLv0TKQ) (14:16)
    + Watch [Lab: Linear Regression](https://www.youtube.com/watch?v=5ONFqIk3RFg) (22:10)
    
* Discuss [Chapter 2 and 3 material](https://stat-ata-asu.github.io/STT3851ClassRepo/Rmarkdown/Chap2Slides.html)

* Homework: 
    +  Reproduce [Lab: Linear Regression (Lab3)](https://stat-ata-asu.github.io/ISLR-CHAP3-LAB-SC/LabChap3-Solution.html) - Accept assignment from GitHub classroom - Due Oct 11
    +  [Data Camp Multiple and Logistic Regression](https://www.datacamp.com/courses/multiple-and-logistic-regression) - Due Oct 18
    +  Reproduce [Data Camp Multiple and Logistic Regression (DataCamp2)](https://stat-ata-asu.github.io/MultipleAndLogisticRegression/) - Accept assignment from GitHub Classroom - Due Oct 25

**Oct 11:**

* Before class:  Review pages 82-120 [ISLR](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf)
  
* Discuss [Chapter 2 and 3 material](https://stat-ata-asu.github.io/STT3851ClassRepo/Rmarkdown/Chap2Slides.html)

* Homework: 
    +  Due TODAY: Reproduce [Lab: Linear Regression (Lab3)](https://stat-ata-asu.github.io/ISLR-CHAP3-LAB-SC/LabChap3-Solution.html) - Accept assignment from GitHub classroom - Due Oct 11
    +  [Data Camp Multiple and Logistic Regression](https://www.datacamp.com/courses/multiple-and-logistic-regression) - Due Oct 18
    +  Reproduce [Data Camp Multiple and Logistic Regression (DataCamp2)](https://stat-ata-asu.github.io/MultipleAndLogisticRegression/) - Accept assignment from GitHub Classroom - Due Oct 25


~~**Oct 14**~~  Fall Break

**Oct 16:**

* Discuss [Chapter 2 and 3 material](https://stat-ata-asu.github.io/STT3851ClassRepo/Rmarkdown/Chap2Slides.html)

* Homework:
    +  [Data Camp Multiple and Logistic Regression](https://www.datacamp.com/courses/multiple-and-logistic-regression) - Due Oct 18
    +  Reproduce [Data Camp Multiple and Logistic Regression (DataCamp2)](https://stat-ata-asu.github.io/MultipleAndLogisticRegression/) - Accept assignment from GitHub Classroom - Due Oct 25
    
**Oct 18:**

* Discuss [Chapter 2 and 3 material](https://stat-ata-asu.github.io/STT3851ClassRepo/Rmarkdown/Chap2Slides.html)

* Homework:
    + Due TODAY: [Data Camp Multiple and Logistic Regression](https://www.datacamp.com/courses/multiple-and-logistic-regression) - Due Oct 18
    +  Reproduce [Data Camp Multiple and Logistic Regression (DataCamp2)](https://stat-ata-asu.github.io/MultipleAndLogisticRegression/) - Accept assignment from GitHub Classroom - Due Oct 25
    
**Oct 21:**

* Discuss [Chapter 2 and 3 material](https://stat-ata-asu.github.io/STT3851ClassRepo/Rmarkdown/Chap2Slides.html)

* Homework:  Reproduce [Data Camp Multiple and Logistic Regression (DataCamp2)](https://stat-ata-asu.github.io/MultipleAndLogisticRegression/) - Accept assignment from GitHub Classroom - Due Oct 25

**Oct 23:**

* Before class:
    + Read the article [_Modeling Home Prices Using Realtor Data_](https://www.tandfonline.com/doi/full/10.1080/10691898.2008.11889569).
    + The data set can be downloaded from http://www.amstat.org/publications/jse/datasets/homes76.dat.txt, while the code book is available from http://www.amstat.org/publications/jse/datasets/homes76.txt
    + Project 1---Accept assignment from GitHub Classroom - Due Nov 8

* Discuss [Chapter 2 and 3 material](https://stat-ata-asu.github.io/STT3851ClassRepo/Rmarkdown/Chap2Slides.html)

* Homework:  Reproduce [Data Camp Multiple and Logistic Regression (DataCamp2)](https://stat-ata-asu.github.io/MultipleAndLogisticRegression/) - Accept assignment from GitHub Classroom - Due Oct 25
    
**Oct 25:**

* Discuss [Chapter 2 and 3 material](https://stat-ata-asu.github.io/STT3851ClassRepo/Rmarkdown/Chap2Slides.html)

* Due TODAY:  Reproduce [Data Camp Multiple and Logistic Regression (DataCamp2)](https://stat-ata-asu.github.io/MultipleAndLogisticRegression/) - Accept assignment from GitHub Classroom - Due Oct 25

**Oct 28:**

* TBD

**Oct 30:**

* TBD

**Nov 1:**

* TBD


**Nov 4:**

* TBD

**Nov 6:**

* TBD

**Nov 8:**

* Due TODAY: Project 1---Accept assignment from GitHub Classroom - Due Nov 8


**Nov 11:**

* Before class:
    + Watch [Linear Model Selection and Best Subset Selection](https://www.youtube.com/watch?v=91si52nk3LA) (13:44)
    + [Forward Stepwise Selection](https://www.youtube.com/watch?v=nLpJd_iKmrE) (12:26)
    + [Backward Stepwise Selection ](https://www.youtube.com/watch?v=NJhMSpI2Uj8) (5:26)
    
Start Project 2 

* [Example Template Directory](https://github.com/STAT-ATA-ASU/STT3851Spring2016/blob/gh-pages/BDbetaTemplate)
* Use the [housedata.csv](https://github.com/STAT-ATA-ASU/STT3851Spring2016/raw/gh-pages/Data/housedata.csv) file - See [King County Housing Data](../Rmarkdown/KingCounty.html)  
* Send an email to the instructor using a subject of "House Data Predictions" with an attached vector (csv file) of your predictions using the data set `housedataTEST.csv`.  Note: your vector should contain 4229 predictions. 

**Nov 13:**

* TBD

**Nov 15:**

* TBD

**Nov 18:**

* TBD


**Nov 22:**

* TBD

**Nov 25:**

* TBD

~~**Nov 27-29:**~~ No Class --- State Holiday

**Dec 2:**

* Send an email to the instructor using a subject of "House Data Predictions" with an attached vector (csv file) of your predictions using the data set `housedataTEST.csv`.  Note: your vector should contain 4229 predictions. LAST DAY to submit new model.

* Work on presentation


**Dec 6:**

* Final presentations 11-1:30; WA 303





